Задача 2.1
hulumulut/TKI-141UNI pull request #10
Opened 2024-02-25 23:09 UTC by hulumulut

Создал новую ветку, исправил документацию, лишних файлов нет

2024-02-27 09:55 UTC, MarinaPaley requested changes

2024-02-27 09:55 UTC, MarinaPaley commented on Task2.1/Main/Main.c
> +* @param заданный пользователем радиус
а где имя `param` (`radius`)?

2024-02-27 09:55 UTC, MarinaPaley commented on Task2.1/Main/Main.c
> +* @param заданный пользователем радиус
также, нет имени параметра

2024-02-27 09:55 UTC, MarinaPaley commented on Task2.1/Main/Main.c
> +*/
а возвращает оа что?

2024-02-27 09:55 UTC, MarinaPaley commented on Task2.1/Main/Main.c
> +    scanf_s("%lf", &radius);
Да, но `scanf_s` возвращает количество введенных чисел, которое нужно проверять! Может быть вводили не число...

2024-02-27 19:23 UTC, hulumulut commented
Добавил описание в документации недостающее описание, также изменил проверку на число для радиуса, введенным пользователем

2024-02-29 09:09 UTC, MarinaPaley approved these changes

2024-02-29 09:09 UTC, MarinaPaley commented on Task2.1/Main/Main.c
> +    radius = get_value();
Лучше писать в одну строку, так как в первом строке получается неинициализированая переменная.

2024-02-29 17:01 UTC, closed without merging