Add files via upload
hulumulut/TKI-141UNI pull request #2
Opened 2023-10-31 12:14 UTC by hulumulut

2023-11-03 06:48 UTC, MarinaPaley requested changes

2023-11-03 06:48 UTC, MarinaPaley commented on Task1.1/Task1.1/Main.c
> +// ������� ��� ������ ��������� a
/
Файл должен быть сохранен в кодировке `UTF-8`

2023-11-03 06:48 UTC, MarinaPaley commented on Task1.1/Task1.1/Main.c
> +#include <locale.h>
Вы все это используете внутри программы?

2023-11-03 06:48 UTC, MarinaPaley commented on Task1.1/Task1.1/Main.c
> +	get_b(1.426, -1.22, 3.5);
нужно ввести константы и передавать их в функцию

2023-11-03 06:48 UTC, MarinaPaley commented on Task1.1/Task1.1/Main.c
> +void get_a(float x, float y, float z)
нет документации

2023-11-07 12:34 UTC, MarinaPaley requested changes

2023-11-07 12:34 UTC, MarinaPaley commented on Task1.1/Task1.1/Main.c
> +void get_a(float x, float y, float z)
Это не документация Нужен `doxygen`

2023-11-07 12:34 UTC, MarinaPaley commented on Task1.1/Task1.1/Main.c
> +	get_b(1.426, -1.22, 3.5);
а где?

2023-11-29 09:36 UTC, MarinaPaley requested changes
Ничего не испарвили

2023-12-15 07:52 UTC, MarinaPaley requested changes

2023-12-15 07:52 UTC, MarinaPaley commented on Task1.1/Task1.1/Main.c
> +void get_a(float x, float y, float z)
Не все параметры функции описаны. если функция называется `get`, тогда от нее ожидается результат.

2023-12-15 07:52 UTC, MarinaPaley commented on Task1.1/Task1.1/Main.c
> +	printf_s("a=%f", a);
1. Реализация должна быть после `main()
2. Не ответственность функции печать что-то

2023-12-15 07:52 UTC, MarinaPaley commented on Task1.1/Task1.1/Main.c
> +	get_b(1.426, -1.22, 3.5);
[Необходимо написать](https://disk.yandex.com.am/i/tcoBg74mwUHasQ)
```c
const double x = ...;
const double y = ...;
const double z = ...;
printf( Здесь напечатать значения x, y, z, a, b);

2023-12-15 07:53 UTC, MarinaPaley requested changes
Отсутствует файл `.gitignore` или неправильно работает!

2023-12-23 08:24 UTC, MarinaPaley requested changes
Отсутствует файл `.gitignore`

2023-12-23 08:24 UTC, MarinaPaley commented on Task1.1/Task1.1/Main.c
> +* @param аргумент a, плюс заданное к нему уравнение
Не описаны все аргументы функции. Написано непонятное "плюс заданное к нему уравнение", где это уравнение передается в функцию?
Отсутствует описание `return`

2023-12-23 08:24 UTC, MarinaPaley commented on Task1.1/Task1.1/Main.c
> +float get_b(float x, float y, float z);
Те же ошибки

2023-12-23 08:24 UTC, MarinaPaley commented on Task1.1/Task1.1/Main.c
> +* @param get_b - параметры x,y,z для поиска аргумента b
Данная функция не имеет (у Вас) аргументов.
Функция возвращает результат, который не описан

2023-12-23 08:24 UTC, MarinaPaley commented on Task1.1/Task1.1/Main.c
> +}
Функция должна возвращать результат.

2023-12-23 08:24 UTC, MarinaPaley commented on Task1.1/Task1.1/Main.c
> +	float a = (2 * cos(x - M_PI / 6)) / ((1 / 2) + pow(sin(y), 2)); // Формула a
Рассчитайте вручную. Ответ будет другой. У Вас ошибка в целочисленном делении!

2024-02-21 14:43 UTC, MarinaPaley requested changes
Не исправлено
Нет '.gitignore'

2024-02-21 21:08 UTC, hulumulut commented
Исправил gitignore, он должен работать

2024-02-25 20:00 UTC, MarinaPaley requested changes
В программе ничего не изменилось. 
Файл `.gitignore` положите в мастер.
Эту ветку перебазируйте (`rebase`) на свежий мастер.

2024-02-25 23:02 UTC, closed without merging