Задача 2.1
hulumulut/TKI-141UNI pull request #3
Opened 2023-11-14 10:15 UTC by hulumulut

2023-11-17 07:56 UTC, MarinaPaley requested changes

2023-11-17 07:56 UTC, MarinaPaley commented on Task2.1/Task2.1/Main.c
> +    }
Это отдельная функция
return 0 когда программа выполнена правильно до конца
сравнение через DBL_EPSILON

2023-11-17 07:56 UTC, MarinaPaley commented on Task2.1/Task2.1/Main.c
> +    scanf_s("%lf", &radius);
не проверяете scanf на неправильный ввод

2023-11-17 07:56 UTC, MarinaPaley commented on Task2.1/Task2.1/Main.c
> +    scanf_s("%d", &choice);
scanf

2023-11-17 07:56 UTC, MarinaPaley commented on Task2.1/Task2.1/Main.c
> +    }
Должен быть case и enum

2023-11-29 09:50 UTC, MarinaPaley requested changes
Структурируйте программу на отдельные функции. Документация!

2023-11-29 09:50 UTC, MarinaPaley commented on Task2.1/Task2.1/Main.c
> +int main() {
Документация

2023-11-29 09:50 UTC, MarinaPaley commented on Task2.1/Task2.1/Main.c
> +    int a = 2.5;
Это константа

2023-11-29 09:50 UTC, MarinaPaley commented on Task2.1/Task2.1/Main.c
> +    scanf_s("%lf", &x);
Должна быть проверка ввода

2023-11-29 09:50 UTC, MarinaPaley commented on Task2.1/Task2.1/Main.c
> +    }
Зачем это?

2023-11-29 09:50 UTC, MarinaPaley commented on Task2.1/Task2.1/Main.c
> +        printf("Значение y с 1ым условием: %lf\n", y);
printf убрать за пределы if

2023-11-29 09:50 UTC, MarinaPaley commented on Task2.1/Task2.1/Main.c
> +    case CONDITION_1:
используйте просто if

2024-02-21 14:36 UTC, MarinaPaley requested changes
1. у Вас не работает `.gitignore`.
2. Проверила первый файл...

2024-02-21 14:36 UTC, MarinaPaley commented on Task2.1/Main/Main.c
> +int get_choice();
нужна документация

2024-02-21 14:36 UTC, MarinaPaley commented on Task2.1/Main/Main.c
> +    puts("Введите 1, если нужен площадь, 2 - если объем: ");
необходимо использовать `enum`, а не 1 или 2

2024-02-21 21:11 UTC, hulumulut commented
Также исправил gitignore, должен работать, добавил документацию(сразу не добавил, ждал проверки сначала самой программы), исправил выбор, теперь есть созависимость данных

2024-02-25 20:06 UTC, MarinaPaley requested changes
Про `.gitignore`. Он не будет так работать. Сделайте rebase на мастер, в который и положите его.

2024-02-25 20:06 UTC, MarinaPaley commented on Task2.1/Main/Main.c
> +* @brief Присваивает значения константам area и volume
1. Никто ничего не присваивает
2. Необходимо для каждой переменной написать что это такое через `brief`

2024-02-25 20:06 UTC, MarinaPaley commented on Task2.1/Main/Main.c
> +* @return завершает программу ошибкой, если вводимое значение не число
Это не `return`, это `remark`.

2024-02-25 20:06 UTC, MarinaPaley commented on Task2.1/Main/Main.c
> +* @brief основная функция
Да, о здесь тоже должен быть `return`.

2024-02-25 20:06 UTC, MarinaPaley commented on Task2.1/Main/Main.c
> +    scanf_s("%lf", &radius);
Результат `scanf_s`нужно проверять.

2024-02-25 20:06 UTC, MarinaPaley commented on Task2.1/Main/Main.c
> +        return 0;
`0` - это код правильного завершения программы!!!!

2024-02-25 20:06 UTC, MarinaPaley commented on Task2.1/Main/Main.c
> +        }
Должен быть еще и `default`.

2024-02-25 23:02 UTC, closed without merging